services:
  web:
    image: igi2024/myparking:latest
    build: .
    ports:
      - "80:80"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-!9^4@k7w#z$1v8r2&b6%q3l0*e5n7s!p@u^x1z2c4g8h5j0k
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/parking_db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: /app/entrypoint.sh
    networks:
      app-network:
        aliases:
          - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=parking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      app-network:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  static_volume:
  media_volume: 