# Generated by Django 4.2.1 on 2025-05-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myparking', '0002_remove_client_user_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='paid_months',
            field=models.PositiveIntegerField(default=0, help_text='Количество оплаченных месяцев'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to=settings.AUTH_USER_MODEL),
        ),
    ]
