# Generated by Django 4.2.1 on 2025-05-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0003_parkingspot_paid_months_alter_parkingspot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3, verbose_name='Валюта'),
        ),
    ]
