# Generated by Django 4.2.1 on 2025-05-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0004_coupon_currency_parkingspot_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
