# Generated by Django 4.2.1 on 2025-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0005_delete_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='support@autocar.by', max_length=254, verbose_name='Email поддержки'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+375 (29) 123-45-67', max_length=20, verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours_weekdays',
            field=models.CharField(default='8:00 - 20:00', max_length=50, verbose_name='Время работы (Пн-Пт)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours_weekends',
            field=models.CharField(default='9:00 - 18:00', max_length=50, verbose_name='Время работы (Сб-Вс)'),
        ),
    ]
