# Generated by Django 4.2.1 on 2025-05-18 20:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0007_alter_companyinfo_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-start_date'], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['number'], 'verbose_name': 'Парковочное место', 'verbose_name_plural': 'Парковочные места'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-start_date'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='support@autocar.by', max_length=254, verbose_name='Email поддержки'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+375 (29) 123-45-67', max_length=20, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_weekdays',
            field=models.CharField(default='8:00 - 20:00', max_length=50, verbose_name='Время работы (Пн-Пт)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_weekends',
            field=models.CharField(default='9:00 - 18:00', max_length=50, verbose_name='Время работы (Сб-Вс)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='cars',
            field=models.ManyToManyField(help_text='Автомобили на парковке', to='myparking.car'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_covered',
            field=models.BooleanField(default=True, help_text='Крытое место'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_heated',
            field=models.BooleanField(default=True, help_text='Отапливаемое место'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_under_surveillance',
            field=models.BooleanField(default=True, help_text='Под видеонаблюдением'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Дата последней оплаты', null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Дата следующей оплаты', null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.PositiveIntegerField(help_text='Номер парковочного места (не более 999)', unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='paid_months',
            field=models.PositiveIntegerField(default=0, help_text='Количество оплаченных месяцев'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'Доллар США')], default='BYN', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(verbose_name='Длительность услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
    ]
