# Generated by Django 4.2.1 on 2025-05-18 21:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0008_alter_companyinfo_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company Info', 'verbose_name_plural': 'Company Info'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-start_date'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['number'], 'verbose_name': 'Parking Spot', 'verbose_name_plural': 'Parking Spots'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-start_date'], 'verbose_name': 'Promo Code', 'verbose_name_plural': 'Promo Codes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='support@autocar.by', max_length=254, verbose_name='Support email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(verbose_name='Company history'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+375 (29) 123-45-67', max_length=20, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(verbose_name='Requisites'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_weekdays',
            field=models.CharField(default='8:00 - 20:00', max_length=50, verbose_name='Working hours (Mon-Fri)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_weekends',
            field=models.CharField(default='9:00 - 18:00', max_length=50, verbose_name='Working hours (Sat-Sun)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, help_text='News summary'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='cars',
            field=models.ManyToManyField(help_text='Cars in parking', to='myparking.car'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_covered',
            field=models.BooleanField(default=True, help_text='Covered spot'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_heated',
            field=models.BooleanField(default=True, help_text='Heated spot'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_under_surveillance',
            field=models.BooleanField(default=True, help_text='Under surveillance'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Last payment date', null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Next payment date', null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.PositiveIntegerField(help_text='Parking spot number (max 999)', unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='paid_months',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid months'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount percent'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(verbose_name='Service duration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Vacancy title'),
        ),
    ]
