# Generated by Django 4.2.1 on 2025-05-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0009_alter_companyinfo_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='parking_spot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='myparking.parkingspot'),
        ),
    ]
