# Generated by Django 4.2.1 on 2025-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0010_remove_parkingspot_cars_car_parking_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='parking_spot',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='cars',
            field=models.ManyToManyField(help_text='Cars in parking', to='myparking.car'),
        ),
    ]
