# Generated by Django 4.2.1 on 2025-05-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myparking', '0011_remove_car_parking_spot_parkingspot_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_spot', to=settings.AUTH_USER_MODEL),
        ),
    ]
