# Generated by Django 4.2.1 on 2025-05-19 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myparking', '0012_alter_parkingspot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='current_parking_spot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parked_car', to='myparking.parkingspot'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to=settings.AUTH_USER_MODEL),
        ),
    ]
