# Generated by Django 4.2.1 on 2025-05-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0013_remove_parkingspot_cars_car_current_parking_spot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='current_parking_spot',
        ),
        migrations.AddField(
            model_name='car',
            name='parking_spot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parked_car', to='myparking.parkingspot'),
        ),
    ]
