# Generated by Django 4.2.1 on 2025-05-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0014_remove_car_current_parking_spot_car_parking_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='is_covered',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='is_heated',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='is_under_surveillance',
        ),
    ]
